// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from main.go:

func InitializeUserController() *UserController {
	database := NewDatabase()
	userService := NewUserService(database)
	userController := NewUserController(userService)
	return userController
}

// main.go:

func main() {
	c := InitializeUserController()
	c.Hello()
}
